# Generated by Django 5.0.4 on 2024-05-03 21:12

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('H:/media')),
        ),
    ]
