# Generated by Django 5.0.4 on 2024-05-03 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='category',
        ),
        migrations.AlterField(
            model_name='journal',
            name='recipe_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='recipe.category'),
            preserve_default=False,
        ),
    ]
