# Generated by Django 5.0.4 on 2024-05-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_journal_date_reged'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='make_time',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
